lsi: false
safe: true
source: .
data_dir: _data
incremental: false
highlighter: rouge

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  

theme: jekyll-theme-cayman
