lsi: false
safe: true
source: .
incremental: false
highlighter: rouge

markdown_ext: "markdown,mkdown,mkdn,mkd,md"

gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  
